### ISSUE TITLE
Reduce start latency to match owlet

### ISSUE THREAD

**Issue by 8bitkick** [8bitkick/BBCMicroBot#41]
Owlet's JSbeeb instance has a breakpoint set at when the OS is first ready for keyboard input. This appears to be at cycle 581402.  At this breakpoint the user program is then written to memory and executed. 

In theory we should be able to adjust the breakpoint timing in client.js of BBCmicrobot (currently 725000) to match this identically. However this will require checking / regeneration of test frame checksums potentially.

(FYI @ojwb who noted some timing differences - these have been reduced from 500ms to ~50ms already but we can get it closer with suggested change above)

**Comment by 8bitkick** [comment]
Adjusted owlet's start time to match the 725000 cycles here instead.

https://github.com/mattgodbolt/owlet-editor/commit/6a58540b69b38bd834e85b935b5dd9ea7b61c6d5

**Comment by ojwb** [comment]
Thanks for working on eliminating these timing differences.  Standardising on 725000 seems reasonable - it's only 0.07 seconds longer when running in real time, which isn't going to be noticeable.

Just to note in case someone wants to revisit this in the future, ~725000 seems to be needed in rocket mode - we think this is because startup is slower (presumably because we end up waiting for I/O from peripherals which appear to be really slow to the emulated machine).  It seems likely this affects the other modes where the bot starts off fast too.

We could use a different number of cycles here for normal mode and the other modes.  Or perhaps start beebjit off slowly and only engage warp speed once we've injected the program.

I suspect the exactly cycle count will also vary at least a little depending what ROMs are loaded.
