### ISSUE TITLE
Emulator stops when focus switches away from tab

### ISSUE THREAD

**Issue by Cthutu** [8bitkick/BBCMicroBot#63]
There are some very long-running programs being written and I'd like to start them then get on with other stuff that I am doing.  However, I've noticed that when the browser's tab loses focus (switching to another or away from the browser itself), the emulator pauses.

Now, I am not sure if this is just the browser doing this.  But if it is the emulator, would it be possible to remove that constraint?

Thanks.

**Comment by ojwb** [comment]
There's no code here which runs in the browser - if you're using the editor at https://bbcmic.ro/ that's https://github.com/mattgodbolt/owlet-editor

However, I think it's standard browser behaviour - I think they initially throttle then pause tabs which aren't in the foreground (otherwise sites with badly written javascript or actively nasty cryptomining-type code would consume resources).

If you have a long running BBC BASIC program beebjit is a better approach than jsbeeb (the emulator in owlet) - for example beebjit can usually run 3 hours of emulated time in well under a minute (the speed-up varies as it depends on what's being emulated).

The code here uses beebjit by default, and has a command line "try" mode which runs for 3 hours before taking a screenshot or recording 3 seconds of video which might be what you want or at least a useful starting point - see the rocket and clapper board emojis in the docs.

**Comment by ojwb** [comment]
No response for two years so closing.  As above, there's nothing here running in-browser, and `beebjit` is likely a better answer than in-browser emulation for anything long running as it's so much faster.
